services:
  hotel-booking:
    build:
      context: ../
      dockerfile: build/docker/hotel.Dockerfile
    container_name: hotel-booking
    networks:
      - service-network
    env_file:
      - ../config/shared/dev.env
      - ../config/hotel-booking/dev.env

  flight-booking:
    build:
      context: ../
      dockerfile: build/docker/flight.Dockerfile
    container_name: flight-booking
    networks:
      - service-network
    env_file:
      - ../config/shared/dev.env
      - ../config/flight-booking/dev.env

  user-service:
    build:
      context: ../
      dockerfile: build/docker/user.Dockerfile
    container_name: user-service
    networks:
      - service-network
    env_file:
      - ../config/shared/dev.env
      - ../config/user-service/dev.env
      
postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - service-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  service-network:
    driver: bridge
