services:
  hotel-booking:
    build:
      context: ../
      dockerfile: build/docker/hotel.Dockerfile
      target: dev
    container_name: hotel-booking-service-dev
    volumes:
      - ../cmd/hotel-booking-service:/hotel-booking-service/cmd/hotel-booking-service
      - ../config/hotel-booking:/hotel-booking-service/config/hotel-booking
      - ../config/shared:/hotel-booking-service/config/shared
      - ../internal/hotel-booking:/hotel-booking-service/internal/hotel-booking
      - ../internal/shared:/hotel-booking-service/internal/shared
      - ../pkg/middlewares:/hotel-booking-service/pkg/middlewares
      - ../pkg/logger:/hotel-booking-service/pkg/logger
      - ../pkg/response:/hotel-booking-service/pkg/response
      - ../pkg/validation:/hotel-booking-service/pkg/validation
    ports:
      - "5100:5100"
    command: ["bin/air", "-c", "/hotel-booking-service/.air.toml"]
    env_file:
      - ../config/shared/dev.env
      - ../config/hotel-booking/dev.env

  flight-booking:
    build:
      context: ../
      dockerfile: build/docker/flight.Dockerfile
      target: dev
    container_name: flight-booking-service-dev
    volumes:
      - "../cmd/flight-booking-service:/flight-booking-service/cmd/flight-booking-service"
      - "../config/flight-booking:/flight-booking-service/config/flight-booking"
      - "../config/shared:/flight-booking-service/config/shared"
      - "../internal/flight-booking:/flight-booking-service/internal/flight-booking"
      - "../pkg/middlewares:/flight-booking-service/pkg/middlewares"
    ports:
      - "6100:6100"
    command: ["bin/air", "-c", "/flight-booking-service/.air.toml"]
    env_file:
      - ../config/shared/dev.env
      - ../config/flight-booking/dev.env

  user-service:
    build:
      context: ../
      dockerfile: build/docker/user.Dockerfile
      target: dev
    container_name: user-service-dev
    volumes:
      - ../cmd/user-service:/user-service/cmd/user-service
      - ../config/user-service:/user-service/config/user-service
      - ../config/shared:/user-service/config/shared
      - ../internal/user-service:/user-service/internal/user-service
      - ../internal/shared/rabbitmq:/user-service/internal/shared/rabbitmq
      - ../pkg/middlewares:/user-service/pkg/middlewares
      - ../pkg/security:/user-service/pkg/security
    ports:
      - "7100:7100"
    command: ["bin/air", "-c", "/user-service/.air.toml"]
    env_file:
      - ../config/shared/dev.env
      - ../config/user-service/dev.env

  blog-service:
    build:
      context: ../
      dockerfile: build/docker/blog.Dockerfile
      target: dev
    container_name: blog-service-dev
    volumes:
      - ../cmd/blog-service:/blog-service/cmd/blog-service
      - ../config/shared:/blog-service/config/shared
      - ../internal/blog-service:/blog-service/internal/blog-service
      - ../pkg/middlewares:/blog-service/pkg/middlewares
      - ../pkg/security:/blog-service/pkg/security
    ports:
      - "7200:7200"
    command: ["bin/air", "-c", "/blog-service/.air.toml"]
    env_file:
      - ../config/shared/dev.env
      - ../config/blog-service/dev.env

  email-service:
    build:
      context: ../
      dockerfile: build/docker/email.Dockerfile
      target: dev
    container_name: email-service-dev
    volumes:
      - ../cmd/email-service:/email-service/cmd/email-service
      - ../config/email-service:/email-service/config/email-service
      - ../config/shared:/email-service/config/shared
    ports:
      - "8100:8100"
    command: ["bin/air", "-c", "/email-service/.air.toml"]
    env_file:
      - ../config/shared/dev.env

  postgres:
    image: postgres:16-alpine
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - service-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-dev
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - service-network

  redis:
    image: redis:alpine
    container_name: redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

volumes:
  pgdata-dev:
  rabbitmq-data:
  redis-data:
