services:
  hotel-booking:
    build:
      context: ../
      dockerfile: build/docker/hotel.Dockerfile
    container_name: hotel-booking
    ports:
      - "5000:5000"
    networks:
      - service-network
    environment:
      - ENVIRONMENT=development

  flight-booking:
    build:
      context: ../
      dockerfile: build/docker/flight.Dockerfile
    container_name: flight-booking
    ports:
      - "9090:9090"
    networks:
      - service-network
    environment:
      - ENVIRONMENT=development

networks:
  service-network:
    driver: bridge
