version: "3.8"

services:
  hotel-booking:
    build:
      context: .
      dockerfile: build/docker/hotel.Dockerfile
    container_name: hotel-booking
    ports:
      - "8080:8080" # Mapping the port 8080 from container to host machine
    networks:
      - service-network
    environment:
      - ENVIRONMENT=development

  flight-booking:
    build:
      context: .
      dockerfile: build/docker/flight.Dockerfile
    container_name: flight-booking
    ports:
      - "9090:9090" # Mapping the port 9090 from container to host machine
    networks:
      - service-network
    environment:
      - ENVIRONMENT=development

networks:
  service-network:
    driver: bridge
