services:
  hotel-booking:
    build:
      context: ../
      dockerfile: build/docker/hotel.Dockerfile
    container_name: hotel-booking
    networks:
      - service-network

  flight-booking:
    build:
      context: ../
      dockerfile: build/docker/flight.Dockerfile
    container_name: flight-booking
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
