services:
  hotel-booking:
    networks:
      - service-network

  flight-booking:
    networks:
      - service-network

  user-service:
    networks:
      - service-network

  email-service:
    networks:
      - service-network

  pgadmin:
    networks:
      - service-network

  redis:
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
