# Root directory of the project
root = "."

# Temporary directory for built binaries
tmp_dir = "tmp"

# Define build configuration
[build]
  args_bin = []
  bin = "tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/$SERVICE_NAME"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "deployments", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = true
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

# Define which directories to watch
[watcher]
  paths = ["cmd"]
  extensions = ["go"]
  ignore = ["vendor", "node_modules", "logs", "tmp", "migrations", "deployments", "api"]

# Define log settings
[log]
  main_only = false
  silent = false
  time = false

# Define colors for output
[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

# Miscellaneous settings
[misc]
  clean_on_exit = false

# Proxy settings (disabled)
[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

# Screen settings
[screen]
  clear_on_rebuild = false
  keep_scroll = true
