apiVersion: v1
kind: Secret
metadata:
  name: shared-secret
  namespace: default
type: Opaque
data:
  DATABASE_URL: dHJhdmVsLWRiLmNkMnV5dXFvaXF0ei5hcC1zb3V0aC0xLnJkcy5hbWF6b25hd3MuY29t
  DATABASE_USERNAME: cG9zdGdyZXM=
  DATABASE_PASSWORD: cm95YWwtZHVzay0yMA==
  DATABASE_NAME: dHJhdmVsLWRi
  DATABASE_PORT: NTQzMg==
