database:
  host: "localhost"
  port: 5432
  user: "dev_user"
  password: "dev_password"
  db_name: "dev_db"
  ssl: false

aws:
  access_key_id: "dev_aws_access_key_id"
  secret_access_key: "dev_aws_secret_access_key"
  region: "us-west-2"

service:
  host: "localhost"
  port: 5000

logging:
  level: "debug"
  format: "json"
