apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-booking
  labels:
    app: flight-booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight-booking
  template:
    metadata:
      labels:
        app: flight-booking
    spec:
      containers:
        - name: flight-booking
          image: deployments-flight-booking
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef:
                name: database-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flight-booking
spec:
  selector:
    app: flight-booking
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP
