database:
  host: "prod-db-service-name1.example.com"
  port: 5432
  user: "prod_user"
  password: "prod_password"
  db_name: "prod_db"
  ssl: true

aws:
  access_key_id: "prod_aws_access_key_id"
  secret_access_key: "prod_aws_secret_access_key"
  region: "us-east-1"

service:
  host: "prod-service-name1.example.com"
  port: 80

logging:
  level: "info"
  format: "json"
