apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-booking
  labels:
    app: hotel-booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel-booking
  template:
    metadata:
      labels:
        app: hotel-booking
    spec:
      containers:
        - name: hotel-booking
          image: deployments-hotel-booking
          imagePullPolicy: Never
          ports:
            - containerPort: 5100
          envFrom:
            - secretRef:
                name: shared-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5100
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5100
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-booking
spec:
  selector:
    app: hotel-booking
  ports:
    - protocol: TCP
      port: 5100
      targetPort: 5100
  type: ClusterIP
