apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-booking
  labels:
    app: hotel-booking
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel-booking
  template:
    metadata:
      labels:
        app: hotel-booking
    spec:
      containers:
        - name: hotel-booking
          image: my-docker-registry/service-name1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME1_ENV
              valueFrom:
                configMapKeyRef:
                  name: service-name1-config
                  key: SERVICE_NAME1_ENV_VAR
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: service-name1-secrets
                  key: db-url
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-booking
spec:
  selector:
    app: hotel-booking
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
